services:
  learnai-postgres:
    image: postgres:15.3-alpine
    container_name: learnai-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  learnai-dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: learnai-dcs-pgadmin
    restart: always
    depends_on:
      - learnai-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  default:
    name: postgres-learnai-network
    external: true

volumes:
  pgadmin_data:
    driver: local